apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

nameSuffix: -dev

patches:
  - path: replica-patch.yaml
    target:
      kind: Deployment
      name: hello-service

patches:
  - path: replica-patch.yaml
  - path: configmap-patch.yaml
